# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
