# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='City')),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
