# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'permissions': set([('view', 'Can view server status')])},
        ),
    ]
