# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='date_added',
        ),
        migrations.AddField(
            model_name='services',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 11, 12, 6, 20, 685090, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(max_length=255, verbose_name='Service Name'),
        ),
    ]
