sudo: required
language: python
branches:
  only:
  - master
  - dev
python:
  - "3.5"
services:
  - docker

before_install:
  - cp web_variables_example.env web_variables.env
  - cp db_variables_example.env db_variables.env
install:
  - docker-compose up -d db
  - docker-compose up -d web
script: docker-compose run -e TMDB_APIKEY=$TMDB_APIKEY web ./manage.py test
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
