version: '2'
services:
  db:
    image: postgres
    env_file:
      - db_variables.env
  web:
    build: .
    command: /lebaguette/prod.sh
    volumes:
      - .:/lebaguette
    depends_on:
      - db
    env_file:
      - web_variables.env
