version: '3'
services:
  db:
    image: postgres
    env_file:
      - db_variables.env
  web:
    build: .
    command: ./run_web.sh
    volumes:
      - .:/lebaguette
    depends_on:
      - db
    env_file:
      - web_variables.env
