# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('type', models.CharField(choices=[('MV', 'Movie'), ('TV', 'TV Show')], max_length=2)),
                ('released', models.DateField()),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('imdb_id', models.CharField(max_length=255, verbose_name='IMDB ID')),
                ('completed', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
