# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestmedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaitem',
            old_name='type',
            new_name='media_type',
        ),
    ]
