# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestmedia', '0002_auto_20160415_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('released', models.DateField()),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('imdb_id', models.CharField(max_length=255, verbose_name='IMDB ID')),
                ('request_completed', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('released', models.DateField()),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('imdb_id', models.CharField(max_length=255, verbose_name='IMDB ID')),
                ('request_completed', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('show_completed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TVShowEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_title', models.CharField(max_length=255, verbose_name='Episode Title')),
                ('episode_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVShowSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField(unique=True)),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestmedia.TVShow')),
            ],
        ),
        migrations.DeleteModel(
            name='MediaItem',
        ),
        migrations.AddField(
            model_name='tvshowepisode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestmedia.TVShowSeason'),
        ),
    ]
