# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestmedia', '0003_auto_20160420_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshowepisode',
            name='episode_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tvshowseason',
            name='season_number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='tvshowepisode',
            unique_together=set([('season', 'episode_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='tvshowseason',
            unique_together=set([('tv_show', 'season_number')]),
        ),
    ]
