# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestmedia', '0005_tvshowepisode_episode_imdbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshowepisode',
            name='episode_released',
            field=models.DateField(default=datetime.datetime(2016, 4, 21, 9, 57, 53, 309761)),
            preserve_default=False,
        ),
    ]
