# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestmedia', '0006_tvshowepisode_episode_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshowepisode',
            name='episode_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tvshowseason',
            name='season_completed',
            field=models.BooleanField(default=False),
        ),
    ]
