# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestmedia', '0007_auto_20160421_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poster Link'),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='poster_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poster Link'),
        ),
    ]
