# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requestmedia', '0007_auto_20160421_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'New'), ('A', 'Approved'), ('R', 'Rejected'), ('C', 'Completed')], max_length=1)),
                ('request_type', models.CharField(choices=[('TV', 'TV Show'), ('M', 'Movie'), ('EP', 'Episode')], max_length=2)),
                ('datetime_requested', models.DateTimeField(auto_now_add=True)),
                ('datetime_completed', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('episode', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmedia.TVShowEpisode')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poster Link'),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='poster_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poster Link'),
        ),
        migrations.AddField(
            model_name='request',
            name='movie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmedia.Movie'),
        ),
        migrations.AddField(
            model_name='request',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='tv_show',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmedia.TVShow'),
        ),
    ]
