# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestmedia', '0008_auto_20160615_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='datetime_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='datetime_rejected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
