# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestmedia', '0009_auto_20160615_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='request_completed',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='request_completed',
        ),
        migrations.RemoveField(
            model_name='tvshowepisode',
            name='episode_completed',
        ),
    ]
