# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestmedia', '0010_auto_20160615_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster_link',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='poster_link',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='/media/posters/'),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='/media/posters/'),
        ),
    ]
