# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestmedia', '0012_auto_20160615_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'permissions': set([('reject', 'Can reject requests'), ('complete', 'Can complete requests'), ('approve', 'Can approve requests')])},
        ),
    ]
