# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestmedia', '0013_auto_20160616_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'permissions': set([('complete', 'Can complete requests'), ('reject', 'Can reject requests'), ('approve', 'Can approve requests'), ('view', 'Can view requests')])},
        ),
    ]
