# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestmedia', '0014_auto_20160616_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdb_rating',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='imdb_rating',
        ),
    ]
