# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestmedia', '0015_auto_20160620_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('series', 'TV Show'), ('movie', 'Movie'), ('episode', 'Episode')], max_length=2)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('released', models.DateField()),
                ('imdb_id', models.CharField(max_length=255, verbose_name='IMDB ID')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('media_completed', models.BooleanField(default=False)),
                ('season', models.IntegerField()),
                ('episode', models.IntegerField()),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestmedia.MediaItem')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tvshowepisode',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='tvshowepisode',
            name='season',
        ),
        migrations.AlterUniqueTogether(
            name='tvshowseason',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='tvshowseason',
            name='tv_show',
        ),
        migrations.RemoveField(
            model_name='request',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='request',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='request',
            name='tv_show',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='TVShow',
        ),
        migrations.DeleteModel(
            name='TVShowEpisode',
        ),
        migrations.DeleteModel(
            name='TVShowSeason',
        ),
        migrations.AddField(
            model_name='request',
            name='media_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmedia.MediaItem'),
        ),
    ]
