# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestmedia', '0016_auto_20160621_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='episode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='media_type',
            field=models.CharField(choices=[('series', 'TV Show'), ('movie', 'Movie'), ('episode', 'Episode')], max_length=7),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='tv_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmedia.MediaItem'),
        ),
    ]
