# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestmedia', '0018_auto_20160622_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='media_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_request', to='requestmedia.MediaItem'),
        ),
    ]
