# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestmedia', '0019_auto_20160622_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
