# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestmedia', '0020_auto_20160622_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='imdb_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='IMDB ID'),
        ),
    ]
