# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('series', 'TV Show'), ('movie', 'Movie'), ('episode', 'Episode')], max_length=7)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('released', models.DateField(blank=True, null=True)),
                ('imdb_id', models.CharField(max_length=255, unique=True, verbose_name='IMDB ID')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('media_completed', models.BooleanField(default=False)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('episode', models.IntegerField(blank=True, null=True)),
                ('tv_show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmedia.MediaItem')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'New'), ('A', 'Approved'), ('R', 'Rejected'), ('C', 'Completed')], max_length=1)),
                ('datetime_requested', models.DateTimeField(auto_now_add=True)),
                ('datetime_completed', models.DateTimeField(blank=True, null=True)),
                ('datetime_approved', models.DateTimeField(blank=True, null=True)),
                ('datetime_rejected', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('media_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_request', to='requestmedia.MediaItem')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': set([('reject', 'Can reject requests'), ('complete', 'Can complete requests'), ('approve', 'Can approve requests'), ('view', 'Can view requests')]),
            },
        ),
    ]
